export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';

export const SET_COLOR_FILTER = 'SET_COLOR_FILTER';
export const UNSET_COLOR_FILTER = 'UNSET_COLOR_FILTER';

export const SET_PRICE_FILTER = 'SET_PRICE_FILTER';
export const UNSET_PRICE_FILTER = 'UNSET_PRICE_FILTER';
